# Generated by Django 6.0.5 on 2026-05-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='image',
            field=models.ImageField(default='', upload_to='workshop_images/'),
            preserve_default=False,
        ),
    ]
