# Generated by Django 6.0.5 on 2026-05-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_workshop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workshop_images/'),
        ),
    ]
